name: Patch Docker Image

on:
  workflow_call:
    inputs:
      image:
        description: The image name to patch
        required: true
        type: string
      target_image:
        description: The target name of the patched image
        required: true
        type: string
      tag:
        description: The image tag to patch
        required: true
        type: string
      target_tag:
        description: The target tag of the patched image
        required: true
        type: string
      ic_version:
        description: The IC version to label
        required: true
        type: string
      platforms:
        description: The platforms to patch
        required: true
        type: string

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  patch-image:
    name: Patch image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Docker Buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 # v3.8.0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0
        with:
          platforms: arm,arm64,ppc64le,s390x

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@6fc4af4b145ae7821d527454aa9bd537d1f2dc5f # v2.1.7
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.GCR_WORKLOAD_IDENTITY }}
          service_account: ${{ secrets.GCR_SERVICE_ACCOUNT }}

      - name: Login to GCR
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Apply OS patches to Container
        uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355 # v6.10.0
        with:
          file: build/Dockerfile
          context: "."
          target: patched
          tags: "${{ inputs.target_image }}:${{ inputs.target_tag }}"
          platforms: ${{ inputs.platforms }}
          pull: true
          push: true
          build-args: |
            IMAGE_NAME=${{ inputs.image }}:${{ inputs.tag }}
            IC_VERSION=${{ inputs.ic_version }}
