name: Update GitHub Release Draft

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Release branch to update from"
        required: true
        type: string

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}-release-draft
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  variables:
    name: Set variables
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    outputs:
      chart_version: ${{ steps.vars.outputs.chart_version }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.branch }}

      - name: Setup Golang Environment
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: go.mod

      - name: Set Variables
        id: vars
        run: |
          source .github/data/version.txt
          echo "chart_version=${HELM_CHART_VERSION}" >> $GITHUB_OUTPUT

      - name: Output variables
        run: |
          echo chart_version: ${{ steps.vars.outputs.chart_version }}

  update-release-draft:
    name: Update Release Draft
    runs-on: ubuntu-24.04
    needs: [variables]
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.branch }}

      - name: Create/Update Draft
        uses: lucacome/draft-release@5d29432a46bff6c122cd4b07a1fb94e1bb158d34 # v1.1.1
        id: release-notes
        with:
          minor-label: "enhancement"
          major-label: "change"
          publish: false
          collapse-after: 50
          variables: |
            helm-chart=${{ needs.variables.outputs.chart_version }}
          notes-footer: |
            ## Upgrade
            - For NGINX, use the {{version}} images from our [DockerHub](https://hub.docker.com/r/nginx/nginx-ingress/tags?page=1&ordering=last_updated&name={{version-number}}), [GitHub Container](https://github.com/nginxinc/kubernetes-ingress/pkgs/container/kubernetes-ingress), [Amazon ECR Public Gallery](https://gallery.ecr.aws/nginx/nginx-ingress) or [Quay.io](https://quay.io/repository/nginx/nginx-ingress).
            - For NGINX Plus, use the {{version}} images from the F5 Container registry, the [AWS Marketplace](https://aws.amazon.com/marketplace/search/?CREATOR=741df81b-dfdc-4d36-b8da-945ea66b522c&FULFILLMENT_OPTION_TYPE=CONTAINER&filters=CREATOR%2CFULFILLMENT_OPTION_TYPE), the [GCP Marketplace](https://console.cloud.google.com/marketplace/browse?filter=partner:F5,%20Inc.&filter=solution-type:k8s&filter=category:networking), [Azure Marketplace](https://azuremarketplace.microsoft.com/en-gb/marketplace/apps/category/containers?page=1&search=f5&subcategories=container-apps) or build your own image using the {{version}} source code.
            - For Helm, use version {{helm-chart}} of the chart.

            ## Resources
            - Documentation -- https://docs.nginx.com/nginx-ingress-controller/
            - Configuration examples -- https://github.com/nginxinc/kubernetes-ingress/tree/{{version}}/examples
            - Helm Chart -- https://github.com/nginxinc/kubernetes-ingress/tree/{{version}}/deployments/helm-chart
            - Operator -- https://github.com/nginxinc/nginx-ingress-helm-operator
